### ISSUE TITLE
gridDistance is broken

### ISSUE THREAD

**Issue by ethanbb** [hasselmonians/CMBHOME#9]
Hey, thanks for the nice package - it looks like it is going to be useful for visualizing and analyzing my grid cell simulation data.

I'm trying to get the scale and orientation of several grid cell receptive fields. I noticed that the `gridDistance` method on Session is broken - it uses the wrong row and column indices due to `rowInd` and `colInd` being indexed by a permutation vector more than once, putting them in the wrong order.

It would also seem more standard to use the center peak rather than the maximum peak to compute grid scale and orientation (avoiding edge effects).

Has this function been replaced with a different one that I should use instead? If not I'd be glad to make some fixes and submit a pull request!

**Comment by wchapman** [comment]
Thanks for the kind words Ethan! `gridDistance` hasn't been replaced, but you might want to take a look at the properties output from `CMBHOME.Session.Gridness`, which includes several orientation and radius measures. 

If you'd like to do a pull request for gridDistance, please do. Otherwise I'll look into this in the near future.

**Comment by ethanbb** [comment]
OK, thanks for the info about `Gridness` - I'm still exploring the different functions available and I hadn't looked at that one. That being said, it also doesn't seem to quite be working for my purposes, so I think I will go ahead and edit `gridDistance` and submit a PR.
